### PR TITLE
fix(sharded): private room broadcast in dynamic mode

### LINKED ISSUE #524: dynamic subscription mode breaks remote socket.emit()
When using the sharded adapter with `subscriptionMode: "dynamic"`, messages sent to the socket's private room via `socket.emit()` get lost without any warning or error.

It happens because [in this check](https://github.com/socketio/socket.io-redis-adapter/blob/ef5f0da0b4928fd422afc985aec0e233d34400c0/lib/sharded-adapter.ts#L127-L131), such messages look just like any other single-room broadcasts, so `useDynamicChannel` ends up being `true` but private rooms are [excluded here](https://github.com/socketio/socket.io-redis-adapter/blob/ef5f0da0b4928fd422afc985aec0e233d34400c0/lib/sharded-adapter.ts#L84-L87) so there are no subscribers.

I can see a couple of possible solutions here, but none is ideal:
1. Attempt to identify the channel is private during emit, and set `useDynamicChannel` to `false` in such case. I made an attempt on this in #525 but it seems somewhat tricky.
2. Clearly document that `socket.emit()` won't work in this mode.
3. Remove the exception for private rooms and subscribe to them as well.
4. Combination of 2 and 3 - add an option for subscribing to private rooms and document `socket.emit()` won't work without it.

### PR DESCRIPTION
**Pull request by MartinKolarik**
Fixes #524 by adding a check for `expectSingleResponse` flag, which is added for `RemoteSocket` instances [here](https://github.com/socketio/socket.io/blob/54dabe5bffeb705fd006729725dd2fa194f70ecf/lib/broadcast-operator.ts#L491). I couldn't find any documentation about that flag, but it seems to be the only way of identifying this case and it does fix the problem.

### CODE REVIEW

File: lib/sharded-adapter.ts [hunk 1]
```diff
@@ -128,7 +128,8 @@ class ShardedRedisAdapter extends ClusterAdapter {
       this.opts.subscriptionMode === "dynamic" &&
       message.type === MessageType.BROADCAST &&
       message.data.requestId === undefined &&
-      message.data.opts.rooms.length === 1;
+      message.data.opts.rooms.length === 1 &&
+      !message.data.opts.flags.expectSingleResponse;
```
Comment (darrachequesne) [inline lib/sharded-adapter.ts:132]: I'm not sure this is sufficient, since this will only work with RemoteSocket objects, and not when calling `io.to(someSocketId).emit(...)`.

Something like:

```js
const useDynamicChannel =
      this.opts.subscriptionMode === "dynamic" &&
      message.type === MessageType.BROADCAST &&
      message.data.requestId === undefined &&
      message.data.opts.rooms.length === 1 &&
      this.rooms.has(message.data.opts.rooms[0]) &&
      !this.sids.has(message.data.opts.rooms[0]);
```

should work to detect public rooms, but it might exclude public rooms that do not exist on the `io` instance, which kind of defeats the purpose of the dynamic mode...

Comment (MartinKolarik) [reply lib/sharded-adapter.ts:132]: Yes, that's right, I forgot to mention this doesn't fix `.to(id).emit()`, only `socket.emit()` on remote socket instances. I also wasn't sure how big of an issue that part was because the [documentation very clearly says](https://socket.io/docs/v4/server-api/#socketid) you should not use the ID directly in your application - but I have to admit we did exactly that in some places of our app.

I would definitely prefer to fix that case as well, and `this.sids.has()` was the first thing I tried, but it seemed to me that `sids` only contains the local IDs, not remote ones, so it didn't actually fix anything.

Given the information available in the adapter instance, I couldn't think of anything better than checking for the ID format, e.g. "if it has exactly this many characters, it's a private ID" but that would obviously have some false positives.
